### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by jordanbb** [40thieves/webpack-sentry-plugin#65]
When running Webpack for a production build, I'm getting the following error in the console if I set `process.traceDeprecation = true;` in my config :

`(node:16768) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at SentryPlugin.apply <PROJECT PATH>\node_modules\webpack-sentry-plugin\dist\index.js:94:16)`

Currently running:

- Webpack v4.12.0
- Node v8.11.3
- NPM 6.1.0
- webpack-sentry-plugin  v1.15.0

**Comment by schneidmaster** [comment]
Thanks! This isn't much of a surprise -- webpack is in the process of rewriting their whole plugin architecture and we haven't updated how we hook into the build to use the new API. I don't think it's particularly urgent because webpack won't drop support for the existing architecture until the next major version (v5), this is just something that will have to be addressed to make webpack-sentry-plugin work on v5 once it arrives.

**Comment by texmex44** [comment]
Same here

**Comment by schneidmaster** [comment]
This was resolved in #71
