### ISSUE TITLE
Sentry Plugin - StatusCodeError: 401 - "{\"detail\": \"Invalid token\"}"

### ISSUE THREAD

**Issue by devlemire** [40thieves/webpack-sentry-plugin#68]
I've followed the documentation but cannot get past this error.

- I've added the package to my `package.json`.
- I've required the package at the top of my `webpack.prod.conf.js`.
- I've configured the `output` of webpack for source maps:

```
   output: {
      path: config.build.assetsRoot,
      filename: utils.assetsPath('js/[name].js'),
      chunkFilename: utils.assetsPath('js/[id].js')
   },
```

- I've added my new SentryPlugin to the array of plugins

```
      new SentryPlugin({
         // Sentry options are required
         organization: 'devmountain',
         project: 'basecamphub',
         apiKey: 'my_key',

         // Release version name/hash is required
         release: function(hash) {
            return hash // webpack build hash
         }
      })
```

I generated an API key under my User Settings -> Auth Tokens and gave my token all the possible scopes. 

I'm not sure what I'm doing wrong here. I've read material that Auth Tokens are the new API keys? API keys were the old way? 

Any help would be much appreciated. My build fails and always outputs:

```
ERROR in Sentry Plugin: StatusCodeError: 401 - "{\"detail\": \"Invalid token\"}"

  Build failed with errors.

error Command failed with exit code 1.
```

**Comment by Hunter-Gu** [comment]
I have the same problem.

**Comment by ChrisYhP** [comment]
I have the same problem.

**Comment by ChrisYhP** [comment]
if you have your own server , please config  baseSentryURL: 'http://yourhost/api/0'

**Comment by Hunter-Gu** [comment]
I have resolved my problem. The old project's webpack version is 1.x, so i update it.

**Comment by schneidmaster** [comment]
Sorry that I never responded to this issue -- @devlemire are you still having trouble with this? It's difficult for me to help here because we don't do anything fancy with authentication -- we just take your configured auth token and use it to make API calls to Sentry. So issues like this are likely to be something specific to your own configuration (especially if you self-host Sentry). I am closing this out for now, but feel free to follow up if you still have an issue and I can try to offer suggestions.

**Comment by lishaobos** [comment]
i also have this problem
